import company1 from "../src/assets/images/company/facebook-logo.png";
import company2 from "../src/assets/images/company/google-logo.png";
import company3 from "../src/assets/images/company/android.png";
import company4 from "../src/assets/images/company/lenovo-logo.png";
import company5 from "../src/assets/images/company/spotify.png";
import company6 from "../src/assets/images/company/linkedin.png";
import company7 from "../src/assets/images/company/circle-logo.png";
import company8 from "../src/assets/images/company/skype.png";
import company9 from "../src/assets/images/company/snapchat.png";
import company10 from "../src/assets/images/company/shree-logo.png";
import company11 from "../src/assets/images/company/telegram.png";
import company12 from "../src/assets/images/company/whatsapp.png";
export const jobRegions = [
  {
    region: "North America",
    countries: [
      "United States",
      "Canada",
      "Mexico",
      "Cuba",
      "Guatemala",
      "Honduras",
      "Costa Rica",
      "Panama",
    ],
  },
  {
    region: "Europe",
    countries: [
      "Germany",
      "France",
      "Italy",
      "Spain",
      "Netherlands",
      "Poland",
      "Sweden",
      "Belgium",
    ],
  },
  {
    region: "Asia",
    countries: [
      "India",
      "China",
      "Japan",
      "South Korea",
      "Singapore",
      "Malaysia",
      "Indonesia",
      "Thailand",
    ],
  },
  {
    region: "Africa",
    countries: [
      "Nigeria",
      "South Africa",
      "Kenya",
      "Egypt",
      "Ghana",
      "Morocco",
      "Ethiopia",
      "Uganda",
    ],
  },
  {
    region: "South America",
    countries: [
      "Brazil",
      "Argentina",
      "Chile",
      "Colombia",
      "Peru",
      "Venezuela",
      "Ecuador",
      "Bolivia",
    ],
  },
  {
    region: "Oceania",
    countries: [
      "Australia",
      "New Zealand",
      "Papua New Guinea",
      "Fiji",
      "Solomon Islands",
      "Vanuatu",
    ],
  },
];

export const quickLinksData = {
  title: "Quick Links",
  links: [
    { text: "Privacy Policy", href: "/privacy-policy" },
    { text: "Terms & Conditions", href: "/terms-conditions" },
  ],
};

export const popularCountries = {
  popularCountryList: [
    {
      country: "India",
      jobs: 90,
    },
    {
      country: "USA",
      jobs: 40,
    },
    {
      country: "Canada",
      jobs: 30,
    },
    {
      country: "Ireland",
      jobs: 20,
    },
    {
      country: "Switzerland",
      jobs: 25,
    },
    {
      country: "UAE",
      jobs: 31,
    },
    {
      country: "India",
      jobs: 90,
    },
    {
      country: "USA",
      jobs: 40,
    },
    {
      country: "Canada",
      jobs: 30,
    },
    {
      country: "Ireland",
      jobs: 20,
    },
    {
      country: "Switzerland",
      jobs: 25,
    },
  ],
};

export const jobData = [
  {
    id: 1,
    image: company1,
    name: "Facebook",
    title: "Web Designer / Developer",
    country: "Australia",
    city: "Vienna",
    applied: "20",
    vacancy: "40",
    date: "13th Sep 2023",
    salary: "950 - 1100",
    posted: "2",
    jobTime: "Full Time",
    desc: "Looking for an experienced Web Designer for an our company.",
  },
  {
    id: 2,
    image: company2,
    name: "Google",
    title: "Marketing Director",
    country: "Russia",
    city: "Moscow",
    applied: "20",
    vacancy: "40",
    date: "29th Nov 2023",
    salary: "950 - 1100",
    posted: "5",
    jobTime: "Part Time",
    desc: "Looking for an experienced Web Designer for an our company.",
  },
  {
    id: 3,
    image: company3,
    name: "Android",
    title: "Application Developer",
    country: "Germany",
    city: "Berlin",
    applied: "20",
    vacancy: "40",
    date: "29th Dec 2023",
    salary: "950 - 1100",
    posted: "3",
    jobTime: "Remote",
    desc: "Looking for an experienced Web Designer for an our company.",
  },
  {
    id: 4,
    image: company4,
    name: "Lenovo",
    title: "Senior Product Designer",
    country: "Italy",
    city: "Rome",
    applied: "20",
    vacancy: "40",
    date: "13th March 2023",
    salary: "950 - 1100",
    posted: "2",
    jobTime: "WFH",
    desc: "Looking for an experienced Web Designer for an our company.",
  },
  {
    id: 5,
    image: company5,
    name: "Spotify",
    title: "C++ Developer",
    country: "France",
    city: "Paris",
    applied: "20",
    vacancy: "40",
    date: "5th May 2023",
    salary: "950 - 1100",
    posted: "3",
    jobTime: "Full Time",
    desc: "Looking for an experienced Web Designer for an our company.",
  },
  {
    id: 6,
    image: company6,
    name: "Linkedin",
    title: "Php Developer",
    country: "Greece",
    city: "Athens",
    applied: "20",
    vacancy: "40",
    date: "19th June 2023",
    salary: "950 - 1100",
    posted: "7",
    jobTime: "Remote",
    desc: "Looking for an experienced Web Designer for an our company.",
  },
  {
    id: 7,
    image: company7,
    name: "Circle CI",
    title: "Web Designer / Developer",
    country: "China",
    city: "Beijing",
    applied: "20",
    vacancy: "40",
    date: "20th June 2023",
    salary: "950 - 1100",
    posted: "1",
    jobTime: "Full Time",
    desc: "Looking for an experienced Web Designer for an our company.",
  },
  {
    id: 8,
    image: company8,
    name: "Skype",
    title: "Marketing Director",
    country: "Japan",
    city: "Tokyo",
    applied: "20",
    vacancy: "40",
    date: "31th Aug 2023",
    salary: "950 - 1100",
    posted: "2",
    jobTime: "Part Time",
    desc: "Looking for an experienced Web Designer for an our company.",
  },
  {
    id: 9,
    image: company9,
    name: "Snapchat",
    title: "Application Developer",
    country: "Singapore",
    city: "Singapore",
    applied: "20",
    vacancy: "40",
    date: "1th Sep 2023",
    salary: "950 - 1100",
    posted: "4",
    jobTime: "Remote ",
    desc: "Looking for an experienced Web Designer for an our company.",
  },
  {
    id: 10,
    image: company10,
    name: "Walmart",
    title: "Senior Product Designer",
    country: "United States",
    city: "Washington",
    applied: "20",
    vacancy: "40",
    date: "13th May 2023",
    salary: "950 - 1100",
    posted: "3",
    jobTime: "WFH",
    desc: "Looking for an experienced Web Designer for an our company.",
  },
  {
    id: 11,
    image: company11,
    name: "Telegram",
    title: "C++ Developer",
    country: "Spain",
    city: "Madrid",
    applied: "20",
    vacancy: "40",
    date: "13th March 2023",
    salary: "950 - 1100",
    posted: "2",
    jobTime: "Full Time",
    desc: "Looking for an experienced Web Designer for an our company.",
  },
  {
    id: 12,
    image: company12,
    name: "Whatsapp",
    title: "Php Developer",
    country: "Jordan",
    city: "Amman",
    applied: "20",
    vacancy: "40",
    date: "13th June 2023",
    salary: "950 - 1100",
    posted: "5",
    jobTime: "Remote",
    desc: "Looking for an experienced Web Designer for an our company.",
  },
];
